file_to_watch = "/tmp/tailpipe_test.log"
regex_filter = "(error|fatal)"
action = "mail"

[mail]
host = "bear.local"
port = 1025
user = "test_user"
pass = "none"
encryption = "none"    # "none", "ssl", "tls"

addr_from = "sender@local.mailer"
addr_to = ["recipient@mail.somewhere", "another@recipient.mail"]
subject = "Tailpipe Error Message"
template = """
Error on {{.Host}} at {{.Date}}

{{.Text}}

{{if .TailError}}
    There was a tail error:<br>{{.TailError}}<br><br>
{{end}}
"""
