file_to_watch = "/tmp/tailpipe_test.log"
regex_filter = "(error|fatal)"
action = "mail"

[mail]
host = "bear.local"
port = 1025
user = "test_user"
pass = "none"
encryption = "none"    # "none", "ssl", "tls"

addr_from = "tailpipe@watch.local"
addr_to = ["recipient@mail.somewhere"]
subject = "Error on {{.Host}}"
template = """
Date:
{{.Date}}

Message:
{{.Text}}

{{if .TailError}}
There was a tail error:
{{.TailError}}
{{end}}
"""
